name: Resume WebRTC iOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Download Patched WebRTC Source
      uses: actions/download-artifact@v4
      with:
        name: webrtc-ios-patched
        path: webrtc-ios

    - name: Install Dependencies
      run: |
        brew list ninja || brew install ninja
        python3 -m pip install --upgrade pip

    - name: Clone depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$PWD/depot_tools" >> $GITHUB_PATH

    - name: Sync dependencies (in case)
      run: |
        cd webrtc-ios
        gclient sync

    - name: Build WebRTC (iOS)
      run: |
        cd webrtc-ios/src
        gn gen out/ios --args='
          target_os="ios"
          target_cpu="arm64"
          target_environment="device"
          ios_deployment_target="12.0"
          is_component_build=false
          is_debug=false
          symbol_level=0
          use_custom_libcxx=false
          use_xcode_clang=false
          enable_ios_bitcode=false
        '
        ninja -C out/ios

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: webrtc-ios-build
        path: webrtc-ios/src/out/ios
