name: Build WebRTC iOS XCFramework

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        brew list ninja || brew install ninja
        python3 -m pip install --upgrade pip

    - name: Clone depot_tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$PWD/depot_tools" >> $GITHUB_PATH

    - name: Fetch WebRTC (iOS)
      run: |
        mkdir webrtc-ios
        cd webrtc-ios
        fetch --nohooks webrtc_ios
        gclient sync

    - name: Build for Device (arm64)
      run: |
        cd webrtc-ios/src
        gn gen out/ios_arm64 \
          --args='
            target_os="ios"
            target_cpu="arm64"
            target_environment="device"
            is_component_build=false
            is_debug=false
            use_xcode_clang=true
            use_system_xcode=true
          '
        ninja -C out/ios_arm64 sdk

    - name: Build for Simulator (arm64)
      run: |
        cd webrtc-ios/src
        gn gen out/ios_simulator \
          --args='
            target_os="ios"
            target_cpu="arm64"
            target_environment="simulator"
            is_component_build=false
            is_debug=false
            use_xcode_clang=true
            use_system_xcode=true
          '
        ninja -C out/ios_simulator sdk

    - name: Create XCFramework
      run: |
        cd webrtc-ios/src

        mkdir -p xcframework

        DEVICE_LIB=out/ios_arm64/obj/sdk/libwebrtc.a
        SIMULATOR_LIB=out/ios_simulator/obj/sdk/libwebrtc.a

        xcodebuild -create-xcframework \
          -library $DEVICE_LIB \
          -headers sdk \
          -library $SIMULATOR_LIB \
          -headers sdk \
          -output xcframework/WebRTC.xcframework

    - name: Upload WebRTC XCFramework
      uses: actions/upload-artifact@v4
      with:
        name: webrtc-ios-xcframework
        path: webrtc-ios/src/xcframework/WebRTC.xcframework

